# fly.toml app configuration file generated for issue-tracker-backend on 2023-09-11T20:15:26+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "issue-tracker-backend"
primary_region = "sin"

[build]
 
 [deploy]
  release_command = "sh ./release.sh"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
